"""empty message

Revision ID: 90c8ce8289f5
Revises: 
Create Date: 2024-09-22 20:21:40.791062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c8ce8289f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('firts_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firts_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
