"""empty message

Revision ID: e27c413ff8cd
Revises: de9070947368
Create Date: 2024-10-04 11:03:28.566108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27c413ff8cd'
down_revision = 'de9070947368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint('expedientes_client_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('expedientes_client_id_fkey', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###
